# Generated by Django 3.1 on 2024-08-09 08:20

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
                ('odjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
